### ISSUE TITLE
大佬 这个插件会比较耗费Vim启动时间  可不可优化下  你的插件都必须依赖它吗

### ISSUE THREAD

**Issue by huayue369** [iamcco/sran.nvim#2]

**Comment by iamcco** [comment]
我这里没有这个问题，把你的 startuptime log 放上来

**Comment by huayue369** [comment]
<img width="1095" alt="屏幕快照 2019-03-26 下午7 13 23" src="https://user-images.githubusercontent.com/32536764/54992815-484e7e00-4ffb-11e9-8f50-40fa58aac7f9.png">

**Comment by iamcco** [comment]
所以哪里耗时间了？？？

**Comment by huayue369** [comment]
302-240=62 是不是这么算的  不好意思 我也不知道是不是这么看的  如果按我这么算 相对于别的插件加载时间会高了些

**Comment by iamcco** [comment]
看列表头，第一列是时钟，第二列才是耗时

**Comment by huayue369** [comment]
哦哦 谢谢指教 菜了点 不好意思
